version: '3.7'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - '3306:3306'
